export const SET_READING_MODE = 'SET_READING_MODE';

export const SET_ACTIVE = 'SET_ACTIVE';
export const SET_ACTIVE_BOOK = 'SET_ACTIVE_BOOK';
export const SET_ACTIVE_CHAPTER = 'SET_ACTIVE_CHAPTER';
export const SET_ACTIVE_PAGE = 'SET_ACTIVE_PAGE';
export const SET_ACTIVE_VERSE = 'SET_ACTIVE_VERSE';

export const SET_HOVERED_VERSE = 'SET_HOVERED_VERSE';